// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6KIKk4RHBf2EJMamMQwt2e_MCUzpaQE',
    appId: '1:445749962946:android:ca8632c51c7f2b88afb35b',
    messagingSenderId: '445749962946',
    projectId: 'mantra-matrix-d8b2a',
    storageBucket: 'mantra-matrix-d8b2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL14XZrRXoeOSYfTm60gI1awAGbyBIc-A',
    appId: '1:445749962946:ios:286c81127ded6dd1afb35b',
    messagingSenderId: '445749962946',
    projectId: 'mantra-matrix-d8b2a',
    storageBucket: 'mantra-matrix-d8b2a.firebasestorage.app',
    iosBundleId: 'com.mauropot.mantraMatrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL14XZrRXoeOSYfTm60gI1awAGbyBIc-A',
    appId: '1:445749962946:ios:286c81127ded6dd1afb35b',
    messagingSenderId: '445749962946',
    projectId: 'mantra-matrix-d8b2a',
    storageBucket: 'mantra-matrix-d8b2a.firebasestorage.app',
    iosBundleId: 'com.mauropot.mantraMatrix',
  );
}
